name: FISCO-BCOS-DOC
on:
  push:
    branches-ignore:
      - "**-1.3"
      - "**-1.5"
    tags-ignore:
      - v1.*
    paths-ignore:
      - "Changelog.md"
      - "README.md"
  pull_request:
    # branches:
    #     - '**'
  release:
    types: [published, created, edited]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y git curl openssl python3-setuptools
      - name: configure
        run: python --version && pip3 install -r requirements.txt
      # - name: compile
      #   run: make html
      - name: run tests
        run: bash .ci/ci_check.sh
